[profile.default]
src = "src"
out = "out"
libs = ["lib"]
extra-output = ["abi", "metadata"]
extra-output-files = ["abi", "metadata"]

# Grant explicit write permissions
fs_permissions = [
    { access = "read", path = "out/" },
    { access = "read-write", path = "../interface/src/deployments/" }
]